language: node_js
node_js: node

notifications:
    email: false
    slack:
        secure: s6mKHaG150HWO6D6RuG5azXUs+IGhjRyxHTZ764RkH8DxlUCraOIJHmDB0BattkBK/gnV1A5xAVAmdP5uL1u1y7LY2F4OBk5iXj9I15DJpcbdAZJ6K7L1tYC2YypmKOQjFAesx987OZYMuCiQHuSg7UEj9NBQ6yzAcvYCG5+hLcw20uFW3Ietos+gpPPZXw9MMjaxX0xBVL3dEsA+xo2OOBthBOLYkVEnTqVJhAjQU1BDcyJWcYg78CJp+cr5+AuiHyutnWXMvdDp54qT1o1tt2sp+V8fB1M4ATZiWQ4zz1ihW+EjIU/6XFMiUi0wrxRw/mkRn3tXOMJYccZApfmaqB04HaNQ4ATNijXSzaQUBq5QCd2puyHWwOClD7vjjvKBl/7qayhlgenvZ55CfpjQAQ6cBalczgz/uoj3dcVpTduVM2oQDNhpJdJ1s4yQhlV8XCagoZRvbqn16yv7sMeLRyGe+mQYBB/xTkvSDKfxQN0HsaKbjSa+yqbJzn8oVOhAwZUnuPTowpEqoqgOw4b/O5b1cwwHTjRT13xgCzXbXubBwpTjrwUNNjZszIuSuGH0NY5LnOiEwRN31hgu/3o/Y4tXm4hQWs9iC10zdD5nlDGnQzUF/jiIjl8BYAvGPN4Dm1jbUUP2hbYq6yKMo3eoW0yuyUqx+wek9YOe4T/b0g=
